# Generated by Django 3.1.4 on 2020-12-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0004_auto_20201205_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='mult',
            fields=[
                ('lid', models.IntegerField(primary_key=True, serialize=False)),
                ('count', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lid', models.IntegerField(default=True)),
                ('speak', models.FileField(default=True, upload_to='')),
                ('num', models.IntegerField(default=True)),
            ],
        ),
    ]
