# Generated by Django 3.1.4 on 2020-12-05 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_mult_speaker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mult',
        ),
        migrations.DeleteModel(
            name='speaker',
        ),
    ]
