# Generated by Django 3.1.4 on 2020-12-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0008_auto_20201205_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='mult',
            fields=[
                ('lid', models.IntegerField(primary_key=True, serialize=False)),
                ('count', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lid', models.IntegerField()),
                ('speak', models.FileField(upload_to='')),
                ('num', models.IntegerField()),
            ],
        ),
    ]
